# Appveyor's documentation is at https://www.appveyor.com/docs/build-phase/,
#  and a sample configuration file is at https://www.appveyor.com/docs/appveyor-yml/.
#  I have to admit its a bit complex and I don't fully understand it.

version: 1.0.{build}
clone_depth: 1
skip_tags: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

configuration:
- Debug

platform:
- x64
- Win32

image:
- Visual Studio 2015

build: off

#  project: cryptest.sln
#  verbosity: minimal
#  parallel: true

test_script:

- cmd: >-

    copy /y TestScripts\cryptlib.vcxproj .

    copy /y TestScripts\cryptest.vcxproj .

    msbuild /t:Build /p:platform=%platform%;configuration=%configuration% cryptlib.vcxproj

    msbuild /t:Build /p:platform=%platform%;configuration=%configuration% cryptest.vcxproj

    msbuild /t:CopyCryptestToRoot cryptest.vcxproj

    cryptest.exe v

    cryptest.exe tv all

# Right now, we have a few failures that we don't know how to workaround.
#  - https://stackoverflow.com/questions/43441273/how-to-run-vcupgrade-before-appveyor-build
#  - https://stackoverflow.com/questions/43423761/cant-perform-64-bit-testing-under-appveyor

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
